# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: documenta 14 athens webshop
email: athens@documenta.de
description: > # this means to ignore newlines until "baseurl:"
  Paths, routes, and parcours cross and intertwine, as visitors consider the pathways taken by peripatetic thinkers as a point of departure for a reflection on the act of walking. Joining a member of the documenta 14 Chorus, visitors can create their own lines of inquiry, questioning and entering into dialogue as they unravel and unfold documenta 14 together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://athens.documenta.de" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


exclude:
  - bower_components
  - viva-tickets.html

sass:
  sass_dir: bower_components/uikit/scss
  style: :compressed